---
title: "Intro"
output: blogdown::html_page
menu:
  docs:
    parent: "syllabus"
weight: 100
toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Course description

This course aims to train psychology majors to conduct behavioral science using programming tools, from building a functioning computer-based psychological task to analyzing and presenting data. Academic psychologists increasingly use such tools to support their research, and expect trainees to begin programs with prerequisite programming experience. Industry data scientists frequently work with human behavioral data, and training in behavioral science is key to rigorous, ethical applied science. This course thus aims to _highlight the importance of the relationship between programming skills and "pure" science_ for psychology undergraduates, and _inspire excitement about the uses and joys of programming for psychologists._

## Learning objectives

### Programming literacy

By the end of this course, students will be able to…

- Diagram the parts and functions of a piece of pre-written R code
- Generate code to manipulate a dataset or produce a data visualization
- Identify and debug commonplace R errors

### Scientific concepts 

By the end of this course, students will be able to…

- Describe how scientific computing improves the quality of psychological science
- Critique the informativeness of a data visualization
- Assess what research questions a dataset can and cannot answer

## Prerequisites

A semester isn't a very long time, and we have a lot to learn! In order for us to implement psychological science concepts through programming in this class, I must be able to assume that you have a certain amount of prior experience with those concepts.

Therefore, to enroll in this class, you _must_ have taken:

- Introductory psychology
- Introductory statistics

## Course format

This course will consist mainly of interactive code-along lectures, interspersed with solo and group work time on in-class activities and exercises.
